### ISSUE TITLE
Alias instead of start_tmux?

### ISSUE THREAD

**Issue by b-m-f** [nachoparker/smart-tmux-sessions#1]
Hi nacho,

nice script, I have used something similar, just saving the PID.

Is there a specific reason you call `start_tmux` instead of aliasing to tmux?

For example by saving `actual_tmux=$(which tmux)` and using that on https://github.com/nachoparker/smart-tmux-sessions/blob/master/start_tmux.sh#L30 ?

**Comment by nachoparker** [comment]
no specific reason :P
